name: laudo_eletronico
description: A new Flutter project.
version: 2.0.3+25
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0
  material_design_icons_flutter: 3.0.3289
  cupertino_icons: ^0.1.2
  standard:
    git: git@ssh.dev.azure.com:v3/Sazso/Sazso/Standard.Flutter
  camera: ^0.5.6+3
  device_id: ^0.1.3
  shared_preferences: ^0.4.3
  sqflite: ^1.0.0
  path_provider: ^0.4.1
  flutter_masked_text: ^0.7.0
  flutter_native_image: ^0.0.4
  native_device_orientation: ^0.0.4
  connectivity: ^0.4.2
  package_info: ^0.4.0+1
  screen: ^0.0.4
  fab_menu: ^0.0.2
  async: ^2.0.8
  firebase_messaging: ^4.0.0+1
  flutter_local_notifications: ^0.5.2
  flutter_xlider: ^2.1.1
  photo_view: ^0.4.2
  image_picker: 0.6.1+4
  month_picker_dialog:
  bloc_pattern: ^2.1.9
  rxdart: ^0.22.0
  get_it: ^1.0.3+2
  intro_slider: ^2.2.5
  auto_size_text: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  
flutter:
  uses-material-design: true
  assets:
    - ./assets/strings/
    - ./assets/images/
    - ./assets/images/marcas/
    - ./assets/images/water_marks/
    - ./assets/images/icons/
    - ./assets/images/tutorial/
